ARG smee_client_version=4.2.1

# pinning base image to specific hash (corresponding to lts-alpine)
FROM node@sha256:f36fed0b2129a8492535e2853c64fbdbd2d29dc1219ee3217023ca48aebd3787
ARG smee_client_version
RUN npm install --global smee-client@${smee_client_version}
ENTRYPOINT ["smee"]
CMD ["--help"]
